# Generated by Django 4.2.2 on 2023-06-11 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0003_alter_provider_age_alter_provider_experience_years'),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationinfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.CreateModel(
            name='providerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='my_users.provider')),
            ],
        ),
    ]
